plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.pulumi:pulumi:1.36.3'
    implementation 'com.pulumi:random:4.21.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'repro.App'
}
